name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: AAP-Classic

      - name: Create Zip
        run: |
          zip -r AAP-classic.zip . -x ".git*" ".github/*"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            AAP-classic.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}